-- CASE 1
SELECT DISTINCT A.CART_ID
FROM (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME LIKE 'Milk') A
JOIN (SELECT CART_ID
      FROM CART_PRODUCTS
      WHERE NAME LIKE 'Yogurt') B
ON A.CART_ID = B.CART_ID
ORDER BY CART_ID;

-- CASE 2
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME='Milk'
AND CART_ID IN (SELECT CART_ID
                FROM CART_PRODUCTS
                WHERE NAME='Yogurt');