SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM (SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME, INS.SEX_UPON_INTAKE, OUTS.SEX_UPON_OUTCOME
      FROM ANIMAL_INS AS INS
      JOIN ANIMAL_OUTS AS OUTS
      ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
      WHERE INS.SEX_UPON_INTAKE LIKE 'Intact%') AS A
WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY ANIMAL_ID